[package]
name = "hello_freetonia"
version = "0.1.0"
authors = ["alex@freetonia.ru"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
